# Generated by Django 5.0.8 on 2025-06-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="grade",
            new_name="pramlearnap_student_f106e0_idx",
            old_name="grades_student_c510f4_idx",
        ),
        migrations.RenameIndex(
            model_name="grade",
            new_name="pramlearnap_student_a61f97_idx",
            old_name="grades_student_e66109_idx",
        ),
        migrations.AlterModelTable(
            name="achievement",
            table=None,
        ),
        migrations.AlterModelTable(
            name="grade",
            table=None,
        ),
        migrations.AlterModelTable(
            name="gradestatistics",
            table=None,
        ),
    ]
