# Generated by Django 5.0.8 on 2025-06-15 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupquiz",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupquizresult",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupquizsubmission",
            name="submitted_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="groupquiz",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groupquiz",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="groupquizresult",
            name="group_quiz",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="pramlearnapp.groupquiz",
            ),
        ),
        migrations.AlterField(
            model_name="groupquizsubmission",
            name="group_quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="pramlearnapp.groupquiz",
            ),
        ),
    ]
