# Generated by Django 5.0.8 on 2025-06-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0002_material_created_at_material_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmotivationprofile",
            name="motivation_level",
            field=models.CharField(
                blank=True,
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
