# Generated by Django 5.0.8 on 2025-06-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pramlearnapp",
            "0002_groupquiz_is_completed_groupquizresult_completed_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupquizsubmission",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
