# Generated by Django 5.0.8 on 2025-06-04 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pramlearnapp', '0002_quiz_slug_studentquizattempt_studentquizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignmentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_answers', models.JSONField(blank=True, default=dict)),
                ('uploaded_files', models.JSONField(blank=True, default=list)),
                ('last_saved', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pramlearnapp.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_assignment_drafts',
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
