# Generated by Django 5.0.8 on 2025-06-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0004_auto_20250625_1938"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="duration",
            field=models.PositiveIntegerField(
                default=0, help_text="Durasi quiz dalam menit"
            ),
        ),
    ]
