# Generated by Django 5.0.8 on 2025-06-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0004_assignmentsubmission_is_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="is_draft",
        ),
    ]
