# Generated by Django 5.0.8 on 2025-06-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0005_quiz_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Quiz aktif/non-aktif"),
        ),
    ]
