# Generated by Django 5.0.8 on 2025-06-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0005_remove_assignmentsubmission_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
