# Generated by Django 5.0.8 on 2025-06-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pramlearnapp', '0006_schedule_studentactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['due_date']},
        ),
    ]
