# Generated by Django 5.0.8 on 2025-06-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0006_assignmentsubmission_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
