# Generated by Django 5.0.8 on 2025-06-28 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0006_quiz_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARCSQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "questionnaire_type",
                    models.CharField(
                        choices=[
                            ("pre", "Pre-Assessment"),
                            ("post", "Post-Assessment"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_arcs_questionnaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arcs_questionnaires",
                        to="pramlearnapp.material",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ARCSQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("attention", "Attention"),
                            ("relevance", "Relevance"),
                            ("confidence", "Confidence"),
                            ("satisfaction", "Satisfaction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("likert_5", "Likert Scale 1-5"),
                            ("likert_7", "Likert Scale 1-7"),
                            ("multiple_choice", "Multiple Choice"),
                            ("text", "Text Input"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("is_required", models.BooleanField(default=True)),
                ("choice_a", models.CharField(blank=True, max_length=255, null=True)),
                ("choice_b", models.CharField(blank=True, max_length=255, null=True)),
                ("choice_c", models.CharField(blank=True, max_length=255, null=True)),
                ("choice_d", models.CharField(blank=True, max_length=255, null=True)),
                ("choice_e", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="pramlearnapp.arcsquestionnaire",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("questionnaire", "order")},
            },
        ),
        migrations.CreateModel(
            name="ARCSResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="pramlearnapp.arcsquestionnaire",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arcs_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("questionnaire", "student")},
            },
        ),
        migrations.CreateModel(
            name="ARCSAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likert_value", models.IntegerField(blank=True, null=True)),
                ("choice_value", models.CharField(blank=True, max_length=1, null=True)),
                ("text_value", models.TextField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pramlearnapp.arcsquestion",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="pramlearnapp.arcsresponse",
                    ),
                ),
            ],
            options={
                "unique_together": {("response", "question")},
            },
        ),
    ]
