# Generated by Django 5.0.8 on 2025-06-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0007_assignmentsubmission_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="essay_answer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
