# Generated by Django 5.0.8 on 2025-06-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0007_create_arcs_questionnaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="arcsquestion",
            name="scale_label_max",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="arcsquestion",
            name="scale_label_min",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="arcsquestion",
            name="scale_max",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="arcsquestion",
            name="scale_min",
            field=models.IntegerField(default=1),
        ),
    ]
