# Generated by Django 5.0.8 on 2025-06-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0008_assignmentsubmission_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="essay_answer",
        ),
    ]
