# Generated by Django 5.0.8 on 2025-06-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0008_update_arcs_question_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="arcsquestionnaire",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Durasi maksimal pengisian dalam menit", null=True
            ),
        ),
        migrations.AddField(
            model_name="arcsquestionnaire",
            name="end_date",
            field=models.DateTimeField(
                blank=True, help_text="Batas waktu pengisian kuesioner", null=True
            ),
        ),
        migrations.AddField(
            model_name="arcsquestionnaire",
            name="start_date",
            field=models.DateTimeField(
                blank=True, help_text="Waktu mulai kuesioner dapat diisi", null=True
            ),
        ),
    ]
