# Generated by Django 5.0.8 on 2025-06-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0009_remove_assignmentsubmission_essay_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentanswer",
            name="essay_answer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
