# Generated by Django 5.0.8 on 2025-06-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pramlearnapp', '0009_quiz_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactivity',
            name='description',
        ),
    ]
