# Generated by Django 5.0.8 on 2025-06-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0009_add_time_limits_to_arcs_questionnaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arcsquestionnaire",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
