# Generated by Django 5.0.8 on 2025-06-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0010_alter_arcsquestionnaire_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="google_form_embed",
        ),
        migrations.RemoveField(
            model_name="material",
            name="google_form_embed_arcs_akhir",
        ),
        migrations.RemoveField(
            model_name="material",
            name="google_form_embed_arcs_awal",
        ),
    ]
