# Generated by Django 5.0.8 on 2025-06-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0010_assignmentanswer_essay_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentquestion",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
