# Generated by Django 5.0.8 on 2025-06-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0011_assignmentquestion_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
