# Generated by Django 5.0.8 on 2025-06-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pramlearnapp", "0012_assignment_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupquiz",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="groupquiz",
            unique_together={("quiz", "group")},
        ),
    ]
