# Generated by Django 5.0.8 on 2025-06-06 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pramlearnapp', '0012_studentmaterialbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaterialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('content_index', models.IntegerField()),
                ('content_id', models.CharField(blank=True, max_length=100)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pramlearnapp.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'material', 'activity_type', 'content_index')},
            },
        ),
    ]
