# Generated by Django 5.0.8 on 2025-06-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pramlearnapp', '0013_studentmaterialactivity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmaterialactivity',
            unique_together={('student', 'material', 'activity_type', 'content_id')},
        ),
    ]
